# Generated by Django 5.1.4 on 2025-09-09 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='category',
        ),
    ]
