# Generated by Django 5.1.4 on 2025-09-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_request_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='category',
            field=models.CharField(choices=[('Квартира', 'Квартира'), ('Дом', 'Дом'), ('Офис', 'Офис'), ('Коммерческое помещение', 'Коммерческое помещение')], default='Квартира', max_length=50),
        ),
    ]
